[mlir][test] Remove unused lambda capture 'this' in UtilsTest.cpp (NFC)
/data/llvm-project/mlir/unittests/Analysis/Presburger/UtilsTest.cpp:39:17: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  auto merge = [this](unsigned i, unsigned j) -> bool { return true; };
                ^~~~
/data/llvm-project/mlir/unittests/Analysis/Presburger/UtilsTest.cpp:52:17: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  auto merge = [this](unsigned i, unsigned j) -> bool { return true; };
                ^~~~
2 errors generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>