Revert "[FPEnv][X86] Platform-specific builtin constrained FP enablement"
This reverts commit 27096398f3bcffba339ff69f1f2be0652c180fe6.

Tests fail:
error: unable to create target: 'No available targets are compatible with triple "x86_64-apple-darwin"'

This happens on clang-hexagon-elf, clang-cmake-armv7-quick, and
clang-cmake-armv7-quick bots.

If anyone has any suggestions on why then I'm all ears.

Differential Revision: https://reviews.llvm.org/D73570

Revert "[FPEnv][X86] Speculative fix for failures introduced by eda495426."

This reverts commit 9a63b709142c849ce71a739908f35224da95b3cd.

The speculative fix didn't solve the test failures on Hexagon, ARMv6, and
MSVC AArch64.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>