[lldb] Handle clang::Language::CIR (#86234)
commit a52f3ab061f173e7f64ee78937285b59a1817eaa
  Author: Nathan Lanza <nathanlanza@gmail.com>
  Date:   Thu Mar 21 19:53:48 2024 -0400

triggers:

  lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp:478:16:
  error: enumeration value 'CIR' not handled in switch
  [-Werror,-Wswitch]

This patch teaches lldb to handle clang::Language::CIR the same way as
clang::Language::LLVM_IR.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>