Revert [lit] Synthesize artificial deadline
Python on Windows raises this OverflowError:
      gotit = waiter.acquire(True, timeout)
  OverflowError: timestamp too large to convert to C _PyTime_t

So it seems this API behave the same way on every OS.

Also reverts the dependent commit 8f68a5f6a5010e589fd8d1328e943a8244247f96.

llvm-svn: 375143
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>