Revert "[CodeGen] Extend reduction support in ComplexDeinterleaving pass to support predication"
ComplexDeinterleavingPass.cpp:1849:3: error: default label in switch which covers all enumeration values

This reverts commit 1c23f357130a2380e11db23cda2ab80b578faaae.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>