Revert "Use-after-return sanitizer binary metadata"
This reverts commit 8c2d316f0b26c63567c1bff26d07d27328f9d201.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>