[Transforms] Fix an unused variable warning
This patch fixes:

  llvm/lib/Transforms/Utils/AMDGPUEmitPrintf.cpp:415:18: error: unused
  variable 'StBuff' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>