Revert "Move DroppedVariableStatsIRTest.cpp to CodeGen folder"
This reverts commit d0ff271044ec9b393077c5af772060fe5b54c831.

Revert "Reland 2352aad2a6887fcab0131355e376117231810adc (#119650)"

This reverts commit 1118fba591c41bfb21101e8184687e29d3b2e7fe.

This is because the clang-ppc64le-linux-multistage bot breaks with error

undefined reference to `vtable for llvm::DroppedVariableStatsIR'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>