Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit f7e3d237c17a383d9175fcee5a0c787f99040586.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>