Revert "[flang] Fix seg fault `CodeGenAction::executeAction()` (#78269)" (#78667)
This reverts commit 27ba12af87d732c4565071d696ae7aab6235527d.

Temporarily until I reproduce and fix a linker issue:
```
FAILED: tools/flang/unittests/Frontend/FlangFrontendTests
...
/usr/bin/ld: tools/flang/unittests/Frontend/CMakeFiles/FlangFrontendTests.dir/CodeGenActionTest.cpp.o: undefined reference to symbol '_ZN4llvm11LLVMContextC1Ev'
/usr/bin/ld: /work1/omp-nightly/build/git/trunk18.0/build/llvm-project/lib/libLLVMCore.so.18git: error adding symbols: DSO missing from command line
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>