[lldb] try to fix build on linux after fd8d2c8b1d68b
Tries to fix:

    ../../lldb/source/Breakpoint/WatchpointResource.cpp:59:12:
    error: no member named 'find' in namespace 'std'; did you mean 'fill'?
          std::find(m_constituents.begin(), m_constituents.end(), wp_sp);
          ~~~~~^~~~
               fill

(cherry picked from commit 5a37be8d711c5cccd6e07847ec944818f80935d1)
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>