Revert "[InstCombine] Add support for max(a,b) + min(a,b) => a + b."
Revert commit due to failure on buildbot:
error: 'match_combine_or' may not intend to support class template argument deduction

This reverts commit 0ff4beefb831128a3f383ddabf0099270753dcbb.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>