[Modules] Exclude InstrumentorRuntimeHelper.h from LLVM_Transforms (#215843)
57cdcb55569dde8ce579cd4dfdd5f361e21ee2d3
(https://github.com/llvm/llvm-project/pull/199329) added
`llvm/Transforms/IPO/InstrumentorRuntimeHelper.h` under the umbrella
directory of the `LLVM_Transforms` clang module. That header is not a
normal C++ API header: it is read as a string at build time (via
`file(READ)` in CMake) and embedded into the instrumentor runtime, and
it includes the C standard headers
`<stdint.h>`/`<string.h>` inside an `extern "C"` block. In Swift's C++
interoperability mode, the includes resolve to the C++
`std_stdint_h`/`std_string_h` modules, which cannot be imported within
an `extern "C"` linkage specification.

```
InstrumentorRuntimeHelper.h:21:1: error: import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification
 17 | #ifdef __cplusplus
 18 | extern "C" {
    | `- note: extern "C" language linkage specification begins here
 19 | #endif
 20 |
 21 | #include <stdint.h>
    | `- error: import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification
```

Exclude the header from `LLVM_Transforms`, mirroring the existing
exclusion of `InstructionWorklist.h`. Since the header is only consumed
as an embedded string and is not included by any other LLVM header, it
never needs to be part of the module's API surface.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>