[lldb] Add missing signal include for TestMultipleDebuggers.py
Fixes multi-process-driver.cpp:221:19: error: use of undeclared
identifier 'SIG_IGN'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>