Revert "[lld] Add support for other demanglers other than Itanium"
This reverts commit ca9622de9b8d5c72c59f79b37ca9ad0613e307c8.

clang-ppc64le-rhel buildbot failed (https://lab.llvm.org/buildbot#builders/57/builds/13424):

    tools/lld/MachO/CMakeFiles/lldMachO.dir/Symbols.cpp.o: In function `lld::demangle(llvm::StringRef, bool)':
    Symbols.cpp:(.text._ZN3lld8demangleEN4llvm9StringRefEb[_ZN3lld8demangleEN4llvm9StringRefEb]+0x90): undefined reference to `llvm::demangle(std::string const&)'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>