[GlobalISel] Fix warnings
This patch fixes:

  llvm/lib/CodeGen/GlobalISel/CombinerHelperCasts.cpp:167:21: error:
  unused variable 'DL' [-Werror,-Wunused-variable]

  llvm/lib/CodeGen/GlobalISel/LoadStoreOpt.cpp:320:15: error: unused
  variable 'DL' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>