[LoongArch] Fix a warning
This patch fixes:

  llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp:561:7: error:
  unused variable 'ScalarSizeInBits' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>