[TableGen] Fix the build
This patch fixes:

  llvm/utils/TableGen/Common/CodeGenRegisters.cpp:653:57: error:
  'getValues' is deprecated: Use getElements instead
  [-Werror,-Wdeprecated-declarations]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>