Revert "Threading: Convert Optional to std::optional"
This reverts commit 1b5a7b0684aa96fec057b04f86d93e820c1fdd2c.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>