[bazel] Add missing deps for #141864 (#142437)
Added in 9fed5943db7dd40618991961e598aa1e3d066061.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>