[mlir][spirv] Update example of `spirv.Constant`(NFC) (#127030)
Actually the `spirv.Constant dense<[2, 3]> : vector<2xf32>` will cause a
error:
```
error: unexpected decimal integer literal for a floating point value
    %cst = spirv.Constant dense<[2, 3]> : vector<2xf32>
                                 ^
```
The value should be an explicit float.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>