[sanitizer_common] Make sanitizer_linux.cpp kernel_stat* handling Linux-specific
9af3362dbef8788b1b4f4b55172172339678f201 broke the Solaris/sparcv9 buildbot:
```
compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:39:14: fatal error: 'asm/unistd.h' file not found
   39 | #    include <asm/unistd.h>
      |              ^~~~~~~~~~~~~~
```
That section should have been Linux-specific in the first place, which is
what this patch does.

Tested on sparcv9-sun-solaris2.11.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>