[X86] Fix an unused variable warning (NFC)
/llvm-project/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:3090:7:
 error: unused variable 'IndexType' [-Werror,-Wunused-variable]
  EVT IndexType = Index.getValueType();
      ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>