Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 6578bc1402f7a41d4af29afbafd689c16ff3df78.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>