Revert "[tsan] Use large address space mapping on Apple Silicon Macs"
This reverts commit 23748f500eae4b1e512e4487528387183e30dd2a.

This patch produces a compile failure on linux amd64 environments, when
running:

  ninja GotsanRuntimeCheck

I get various build errors:

  ../rtl/tsan_platform.h:608: error: use of undeclared identifier 'Mapping'
    return MappingImpl<Mapping, Type>();

Here's a buildbot with the same failure during stage "check-tsan in gcc
build", there are other unrelated failures in there.

  http://lab.llvm.org:8011/#/builders/37/builds/2831
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>