Revert [llvm] annotate ABIBreakingChecks symbols for DLL export (#147965)
This patch reverts commit 57b08d1b33d1bac68780b8bf3a14f93aab07cf76. The
change introduced a cyclic dependency:
```
fatal error: cyclic dependency in module 'LLVM_Utils': LLVM_Utils -> LLVM_Config_ABI_Breaking -> LLVM_Utils
```

See failure log at
https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/976/console.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>