Revert "[ubsan] Simplify ubsan_GetStackTrace"
This reverts commit 47af6e00c3ab5bc01b70b32a323ef345c733644e.

I don't quite understand why, but this causes a linker error for
me and a number of buildbots:

/home/npopov/repos/llvm-project/compiler-rt/lib/ubsan/../sanitizer_common/sanitizer_stacktrace.h:130: error: undefined reference to '__sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int)'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>