[MLIR] Use false instead of nullptr for boolean args. (NFC) (#224009)
This fixes a build failure on macOS with -Werror:
error: implicit conversion of nullptr constant to 'bool'
[-Werror,-Wnull-conversion]

PR: https://github.com/llvm/llvm-project/pull/224009
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>