Fixed bot failure after 8459e582a60940096
There were some bot failures due unused funtion `rotateSign`
left in code.

http://lab.llvm.org:8011/builders/clang-ppc64le-rhel/builds/3731

error: unused function 'rotateSign' [-Werror,-Wunused-function]
static uint64_t rotateSign(int64_t I)
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>