Remove unused variable 's8' in X86LegalizerInfo.cpp (NFC)
/data/llvm-project/llvm/lib/Target/X86/X86LegalizerInfo.cpp:443:13: error: unused variable 's8' [-Werror,-Wunused-variable]
  const LLT s8 = LLT::scalar(8);
            ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>