[Transforms] Fix a warning
This patch fixes:

  llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:1112:13: error:
  unused function 'dumpUnpackedICmp' [-Werror,-Wunused-function]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>