[lldb] Fix "NameError: name 'self' is not defined" when using crashlog -c
This fixes a regression introduced by e046085a0688 that results in a
NameError: (name 'self' is not defined) when using crashlog with the -c
option.

rdar://110007391
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>