Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit 573943c9aedb5d4d695090fae9124e5b49c5ffc6.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>