Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit 3a5d92e5200e01fd9f2b7af7530913dcf048f66b.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>