Revert "[test] Speculative fix for bots"
This reverts commit 06d46443a4c4bc1534ddfa8a620731732c719ae5.

unittests/Passes/CMakeFiles/PassesBindingsTests.dir/PassBuilderBindingsTest.cpp.o: In function `PassBuilderCTest::SetUp()':
PassBuilderBindingsTest.cpp:(.text._ZN16PassBuilderCTest5SetUpEv[_ZN16PassBuilderCTest5SetUpEv]+0x28): undefined reference to `LLVMInitializeARMTargetInfo'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>