Revert "Frontend: Sink named pipe logic from CompilerInstance down to FileManager"
This reverts commit c697b4f8b03ecf914124ef2e0c714da9632948cf, since
apparently this doesn't work everywhere. E.g.,
clang-x86_64-debian-fast/3889
(http://lab.llvm.org:8011/#/builders/109/builds/3889) gives me:
```
+ : 'RUN: at line 8'
+ /b/1/clang-x86_64-debian-fast/llvm.obj/bin/clang -x c /dev/fd/0 -E
+ cat /b/1/clang-x86_64-debian-fast/llvm.src/clang/test/Misc/dev-fd-fs.c
fatal error: file '/dev/fd/0' modified since it was first processed
1 error generated.
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>