Revert "Move DroppedVariableStats to CodeGen lib (#120650)"
This reverts commit 72a79248965bdd761e6ea1672a628cd7ec3b9924.

Broke bot ppc64le-clang-multistage-test:

undefined reference to
`llvm::DroppedVariableStats::populateVarIDSetAndInlinedMap in
In function `llvm::DroppedVariableStatsIR::visitEveryInstruction
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>