Revert "Try to unbreak Win build differently after 92ecbd2926270a"
Breaks the build and failed pre-merge checks:
https://buildkite.com/llvm-project/premerge-checks/builds/54930#07373971-3d37-49cf-9def-22c0d724ee23

> llvm-project/lld/wasm/Writer.cpp:521:16: error: non-const lvalue reference to
>  type 'llvm::StringRef' cannot bind to a temporary of type 'llvm::StringRef'
>    for (auto &feature : used.keys()) {

This reverts commit a6a349db394a030843d26deaf869d7f016604b33.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>