[bazel][libc][NFC] Add missing layering deps (#107947)
After ced6916956bb57e942a62822d174e37a78d25a65

e.g.

```
external/llvm-project/libc/test/src/math/smoke/NextTowardTest.h:12:10: error: module llvm-project//libc/test/src/math/smoke:nexttowardf_test does not depend on a module exporting 'src/__support/CPP/bit.h'
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>