[lldb][test] TestFrameVarDILGlobalVariableLookup: XFAIL on older Clang versions
Failing on macOS Clang-15 and Clang-17 bots with:
```
07:26:20  ======================================================================
07:26:20  FAIL: test_frame_var (TestFrameVarDILGlobalVariableLookup.TestFrameVarDILGlobalVariableLookup)
07:26:20  ----------------------------------------------------------------------
07:26:20  Traceback (most recent call last):
07:26:20    File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 156, in wrapper
07:26:20      return func(*args, **kwargs)
07:26:20    File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/commands/frame/var-dil/basics/GlobalVariableLookup/TestFrameVarDILGlobalVariableLookup.py", line 48, in test_frame_var
07:26:20      self.expect_var_path("ExtStruct::static_inline", value="16")
07:26:20    File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2599, in expect_var_path
07:26:20      value_check.check_value(self, eval_result, str(eval_result))
07:26:20    File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 302, in check_value
07:26:20      test_base.assertSuccess(val.GetError())
07:26:20    File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2607, in assertSuccess
07:26:20      self.fail(self._formatMessage(msg, "'{}' is not success".format(error)))
07:26:20  AssertionError: '<user expression 0>:1:1: use of undeclared identifier 'ExtStruct::static_inline'
07:26:20     1 | ExtStruct::static_inline
07:26:20       | ^' is not success
```

I suspect Clang-17 (and earlier) used DWARFv4 on macOS by default. So we
would use the Apple accelerator tables, which didn't index `ExtStruct`
(based on what I observed locally). We already XFAIL this test for
DWARFv4, hence XFAIL it also for older Clang versions.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>