[Driver][test] Change some -fuse-ld=lld tests to be agnostic of host ld.lld
If program paths (GCC installation, --sysroot, -B, etc) don't contain
ld.lld, whether -fuse-ld=lld succeeds depends on whether a PATH
directory contains ld.lld.

> error: invalid linker name in argument '-fuse-ld=lld'

This behavior is not suitable when we adopt the new strict behavior of
-### in D156363.

For some tests, append -B%S/Inputs/lld similar to D92028.
For others, use -fuse-ld=ld so that getDefaultLinker (instead of CLANG_DEFAULT_LINKER) is used. The complexity stems from CLANG_DEFAULT_LINKER.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>