[Transforms] Fix an unused variable warning
  llvm/include/llvm/Transforms/Utils/SampleProfileLoaderBaseImpl.h:89:28:
  error: private field 'LTOPhase' is not used
  [-Werror,-Wunused-private-field]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>