Explicitly convert to double to suppress Visual C++ 2008 build error C2668 pow is ambiguous call to overloaded function
llvm-svn: 85478
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>