Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit ada3aaf41a757ba4abed6932ee8bbbf2619f840b.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>