Revert "[MLIR][SPIRV] Start module combiner."
This reverts commit 5379644e5a78c9f3c1fc01e7ca2124a1a7c4c631.

Shared libs build is broken linking lib/libMLIRSPIRVModuleCombiner.so:

```
ModuleCombiner.cpp:
  undefined reference to `mlir::spirv::ModuleOp::addressing_model()
```

https://buildkite.com/mlir/mlir-core/builds/8988#e3d966b9-ea43-492e-a192-b28e71e9a15b
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>