[bazel] Add missing deps for #141864 (#142437)
Added in 26f557e04c78aa5d7412a2ec4f39695361acf15a.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>