Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit 24dfb68d63ca2493b8aebe1d6d9271b339bd08d7.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>