Revert "Try to unbreak Win build differently after 88b06992afd2bf"
Breaks the build and failed pre-merge checks:
https://buildkite.com/llvm-project/premerge-checks/builds/54930#07373971-3d37-49cf-9def-22c0d724ee23

> llvm-project/lld/wasm/Writer.cpp:521:16: error: non-const lvalue reference to
>  type 'llvm::StringRef' cannot bind to a temporary of type 'llvm::StringRef'
>    for (auto &feature : used.keys()) {

This reverts commit 077f8b737a7be5e142a401996345f7d2c5956e12.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>