[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/9cc137ffd310636968650a7ce36a06bf004fb90c/clang/include/clang-c/Index.h#L2716),
added in 9cc137ffd310636968650a7ce36a06bf004fb90c.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>