Revert "[libc++][format] Add basic_format_parse_context."
This reverts commit 18bb662785ab3c3d21d54fb77b2ed65e491b96d0.

A build is broken during clang bootstrap with:

In file included from ../libcxx/src/format.cpp:9:
/tmp/ci-nGNyLRM9V3/include/c++/v1/format:153:16: error: no member named 'is_constant_evaluated' in namespace 'std::__1'
    if (_VSTD::is_constant_evaluated() && __id >= __num_args_)
        ~~~~~~~^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>