[flang][CUF] fix missing header after #112188 (#118993)
Otherwise, builds with `-DFLANG_CUF_RUNTIME` hits:

```
runtime/CUDA/descriptor.cpp:44:24: error: invalid use of incomplete type 'const class Fortran::runtime::Descriptor'
   44 |   std::size_t count{src->SizeInBytes()};
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>