Revert "[mlir][irdl] Support variadicity check in operations"
This reverts commit 67f522731d75889819c259503eb345612dfb3835.

This is the error reported by the buildbot:
 /home/buildbots/ppc64le-flang-rhel-test/ppc64le-flang-rhel-clang-build/llvm-project/mlir/lib/Dialect/IRDL/IRDLLoading.cpp:97:22: error: no member named 'reduce' in namespace 'std'
  int32_t sum = std::reduce(denseSegmentSizes.asArrayRef().begin(),

Full details are available at:
    https://lab.llvm.org/buildbot#builders/21/builds/78689
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>