[bazel] Turn off layering_check for //llvm/unittests:target_aarch64_tests
llvm/unittests/Target/AArch64/AArch64SVESchedPseudoTest.cpp:38:10: error: module @llvm-project//llvm/unittests:target_aarch64_tests does not depend on a module exporting 'AArch64GenInstrInfo.inc'

Test was added in d5a75ef613a559a8ef69dd62f452acc718c25af0
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>