Revert "Move DroppedVariableStatsIRTest.cpp to CodeGen folder"
This reverts commit 555075bda9984fc662bd40ee76adcbbc5f75a660.

Revert "Reland f34f6af5a77be5252a4b4bd7fc3e995d86a18a86 (#119650)"

This reverts commit 95d2827c63681d86c19a9ecb0e3365652835b26f.

This is because the clang-ppc64le-linux-multistage bot breaks with error

undefined reference to `vtable for llvm::DroppedVariableStatsIR'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>