Revert "[AST] Use ModRefInfo to represent access kind (NFC)"
This reverts commit e5e8cfaad3d5d784a97b7ffaf0a9dc48240d27a2.

Fails to compile on mlir-s390x-linux buildbot using GCC 9.4 with:

    llvm/lib/Analysis/AliasSetTracker.cpp: In member function 'void llvm::AliasSet::mergeSetIn(llvm::AliasSet&, llvm::AliasSetTracker&, llvm::BatchAAResults&)':
    llvm/lib/Analysis/AliasSetTracker.cpp:50:19: error: invalid operands of types 'unsigned char:2' and 'unsigned char:2' to binary 'operator|'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>