Revert "Fix amdgpu-arch for dll name on Windows (#101350)"
This reverts commit 88f3688a591a26b5494db7aadf1ff5138433e85c.

Revert it due to breaking buildbot:

Z:\b\llvm-clang-x86_64-sie-win\llvm-project\clang\tools\amdgpu-arch\AMDGPUArchByHIP.cpp(104):
 error C2039: 'parse': is not a member of 'llvm::VersionTuple'

https://lab.llvm.org/buildbot/#/builders/46/builds/13184
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>