[AArch64][GlobalISel] Remove unused variable 'v2s8' in AArch64LegalizerInfo.cpp (NFC)
/Users/jiefu/llvm-project/llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp:53:13: error: unused variable 'v2s8' [-Werror,-Wunused-variable]
  const LLT v2s8 = LLT::fixed_vector(2, 8);
            ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>