[libcxx] Bump __libcpp_version to 14 after branch
This was missed in 9ee50383e69fcfaab046ba3d4a2eb157fc6e784b
and caused test failures in the buildkite bots:
libcpp_version.pass.cpp:22:1:
error: static_assert failed due to requirement '14000 == libcpp_version'
"_LIBCPP_VERSION doesn't match __libcpp_version
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>