Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 606c1ad1bc69be60e58d326775d1d63673843933.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>