[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/e37dca5d5c7d4e6cdb696aa790362613ec0d3d2b/clang/include/clang-c/Index.h#L2716),
added in e37dca5d5c7d4e6cdb696aa790362613ec0d3d2b.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>