revert r101863, whcih is causing Sema/altivec-init.c to fail on a ton of buildbots with:
error: 'error' diagnostics expected but not seen: 
  Line 9: too few elements in vector initialization (expected 8 elements, have 2)
1 warning and 1 error generated.

llvm-svn: 101864
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>