[flang][OpenMP] Remove pessimizing move introduced in da3c119492
This unbreaks the builders that diagnose this situation:

  error: moving a temporary object prevents copy elision [-Werror,-Wpess
imizing-move]
    341 |   static OmpClauseList empty{std::move(decltype(OmpClauseList:
:v){})};
        |                              ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>