Minor unused variable error for sanitizer builds (#132372)
Fix #132371
Minor error ,  sanitizer builds are failing for unused variable.  

sanitizer-aarch64-linux/build/llvm-project/clang/lib/Serialization/ASTReader.cpp:11764:17:
error: unused variable 'I' [-Werror,-Wunused-variable]
 11764 |   for (unsigned I : llvm::seq<unsigned>(NumFlags))

This was modified as part of
[https://github.com/llvm/llvm-project/pull/129938](https://github.com/llvm/llvm-project/pull/129938)
, which got missed.

Co-authored-by: Chandra Ghale <ghale@pe31.hpc.amslabs.hpecorp.net>
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>