Revert "[llc][MISched] Add `-misched-detail-resource-booking` to llc."
Reverting because of https://lab.llvm.org/buildbot#builders/75/builds/32485:

llvm-project/llvm/lib/CodeGen/MachineScheduler.cpp:2374:7: error: use of undeclared identifier 'MischedDetailResourceBooking'
 if (MischedDetailResourceBooking)

This reverts commit f863cb626804ee6e4ea9d39c15d3e78bb15ef9e7.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>