Revert "Use-after-return sanitizer binary metadata"
This reverts commit fc944a3036e33b1eb9693fd9c06f6f580a51f00f.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>