Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 0bb328e9568b2ceef6d4396f2f644550fac7e9bf because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>