Fix 20ccc734594a8f5bbb9c1102b32de35225fff349
Buildbot failed on Windows
http://lab.llvm.org:8011/#/builders/83/builds/693

Error: On Windows, std::future can't hold an Expected, as it doesn't have a default
constructor.

Solution: Use std::future<bool> instead of std::future<Expected<T>>
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>