[bazel][mlir] Add missing dep and include after 0eb188fccde45e28a196a9db9e36bd38c8c5f6be
This fixes issues when compiling SliceMatchers.h separately. In
particular, the missing include triggered a "member access into
incomplete type" error:

```
third_party/llvm/llvm-project/mlir/include/mlir/Query/Matcher/SliceMatchers.h:91:30: error: member access into incomplete type 'Operation'
   91 |     for (auto operand : subOp->getOperands()) {
      |                              ^
third_party/llvm/llvm-project/mlir/include/mlir/Analysis/SliceAnalysis.h:20:7: note: forward declaration of 'mlir::Operation'
   20 | class Operation;
      |       ^
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>