Revert "[APFloat] Properly implement DoubleAPFloat::convertToSignExtendedInteger"
This reverts commit 9f6537d6026d1464c58d9c5d8c510bc6fa08b8c6.

I'm getting:

llvm/lib/Support/APFloat.cpp:5627:29: error:
use of undeclared identifier 'Parts'
 5627 |     assert(DstPartsCount <= Parts.size() && "Integer too big");
      |                             ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>