[GlobalIsel][X86] Remove unused private field 'TM' in X86LegalizerInfo (NFC)
/data/llvm-project/llvm/lib/Target/X86/X86LegalizerInfo.h:30:27: error: private field 'TM' is not used [-Werror,-Wunused-private-field]
  const X86TargetMachine &TM;
                          ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>