Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit 2f5d5540d8f181fd44a639ed05e25d8287035c86.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>