[RISCV] Fix a warning
This patch fixes:

  llvm/lib/Target/RISCV/MCTargetDesc/RISCVBaseInfo.h:256:18: error:
  unused variable 'TSFlags' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>