Revert "[llvm-(min-)tblgen] Avoid redundant source compilation (#114494)"
This reverts commit e7d808fcc2e6783c40f933f7003b70ef2e1a17f7.

Buildbot failures such as https://lab.llvm.org/buildbot/#/builders/89/builds/13541:
```
/usr/bin/ld: utils/TableGen/Basic/CMakeFiles/obj.LLVMTableGenBasic.dir/ARMTargetDefEmitter.cpp.o: undefined reference to symbol '_ZN4llvm23EnableABIBreakingChecksE'
/usr/bin/ld: /home/tcwg-buildbot/worker/flang-aarch64-libcxx/build/./lib/libLLVMSupport.so.20.0git: error adding symbols: DSO missing from command line
```

Going to investigate.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>