Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit c5cb2e7859b7a5f297d808204f81a4dff0c96cf2.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>