[readtapi] Use ExitOnError instead of errorcodes for `readlink` wrapper
Silences: ` error C4716: 'read_link': must return a value` windows error
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>