Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit cb54444f7c2976c957a6cb6366850d25b3dcfa1b.
Breaks building on Windows:

    ../../lldb/include\lldb/Host/HostNativeThreadBase.h(49,36): error:
        cannot initialize a member subobject of type 'lldb::thread_result_t'
        (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'
      lldb::thread_result_t m_result = nullptr;
                                       ^~~~~~~
    1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>