Revert r205769 as it breaks the build on FreeBSD:
error: declaration of constexpr static data member 'spec' requires an
initializer

llvm-svn: 205776
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>