Revert "[analyzer][NFC] Add unittest for FalsePositiveRefutationBRVisitor"
This reverts commit 54a264ac287c9f03daa9c32c2f089d613844164f. It broke
the build:

FalsePositiveRefutationBRVisitorTest.cpp:112:3: error: use of undeclared identifier 'LLVM_WITH_Z3'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>