[mlir] Revert to old fold logic in IR::Dialect::add{Types, Attributes}() (#79582)
Fold expressions on Clang are limited to 256 elements. This causes
compilation errors in cases when the amount of elements added exceeds
this limit. Side-step the issue by restoring the original trick that
would use the std::initializer_list. For the record, in our downstream
Clang 16 gives:

mlir/include/mlir/IR/Dialect.h:269:23: fatal error: instantiating fold
expression with 688 arguments exceeded expression nesting limit of 256
    (addType<Args>(), ...);

Partially reverts 535508ed3a721ce8c9986177de9f49bf204a6746.

Co-authored-by: Nikita Kudriavtsev <nikita.kudriavtsev@intel.com>
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>