Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 578a8e32204cb98b2027e8e267756c72a91b9ec8 and
349ec675292a7f2f0b76591a940c958f9d2e926d.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>