Revert "[flang] Make 'this_image()' an intrinsic function"
This reverts commit 27c9884051b62b2bc6a377403eee188055ea72f4.
This seems to break the shared libs build
(linaro-flang-aarch64-sharedlibs bot) with:

  undefined reference to `Fortran::semantics::IsCoarray(Fortran::semantics::Symbol const&)

(from tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o)

When linking lib/libFortranEvaluate.so.14git
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>