Revert "Add symbol locator time for each module in statistics (#134563)"
This reverts commit acb6aa3c73cc1bb0ca458bb0dcc664e6df848958.

Multiple buildbot failures have been reported:
https://github.com/llvm/llvm-project/pull/134563

The build fails with:

  lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared
  identifier 'num_symbols_loaded'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>