[SPIRV] Fix unused-variable warnings (NFC)
/llvm-project/llvm/lib/Target/SPIRV/SPIRVLegalizePointerCast.cpp:198:12:
 error: unused variable 'dstBitWidth' [-Werror,-Wunused-variable]
      auto dstBitWidth =
           ^
/llvm-project/llvm/lib/Target/SPIRV/SPIRVLegalizePointerCast.cpp:200:12:
 error: unused variable 'srcBitWidth' [-Werror,-Wunused-variable]
      auto srcBitWidth =
           ^
2 errors generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>