Revert D130308 "[clang] extend getCommonSugaredType to merge sugar nodes"
This reverts commit 91e0ffb46652a05d88506901cd9c03318fcf7276.
There are multiple complaints on the review.

In addition, it may cause spurious
```
error: invalid operands to binary expression ('SinkPrinter' and 'char[cluster_name_length]')
note: candidate template ignored: substitution failure: variably modified type 'char *' cannot be used as a template argument SinkPrinter operator<<(const SinkPrinter &s, T) {
```
for some C++ code
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>