Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit 1eb5e79e268a8ccceac6cc64842cb0ece44a6586.

A bot is broken
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>