Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit f475c3d56af3202d7ab0a5f6b85b93247d0b5eb9.
This reverts commit d94c6728c4d2029a712776975a283337953d0ae6.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>