Revert "lit: revert 252a25721c25436beaa094395b897cad49a5bc8d"
This reverts commit 7a7fe810939ccd8d166d7d861523ede45af35005.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>