[SPIR-V] Add missing ScalarOpts library (#114384)
Fixes an "undefined reference to `llvm::createRegToMemWrapperPass()'"
linker error introduced by f83ac454b61a ("[SPIR-V] Fix BB ordering &
register lifetime (#111026)", 2024-10-30).
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>