Revert "[CodeGen] Extend reduction support in ComplexDeinterleaving pass to support predication"
ComplexDeinterleavingPass.cpp:1849:3: error: default label in switch which covers all enumeration values

This reverts commit 7181636be0a15e616bee450968ef3d4803c5858c.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>