Revert "[RISCV] AddEdge between mask producer and user of V0 (#146855)"
This reverts commit adefe823eb05ee278838ed5c05930937017a6b85.

As noted
<https://github.com/llvm/llvm-project/pull/146855#issuecomment-3061784904>
this causes compile errors for several RVV configurations:

    fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>