<rdar://problem/12897145>
Changes to lldb made the following fail when it used to work:

% cd /tmp
% lldb ls
error: unable to find executable for '/tmp/ls'

Resolving an executable with no relative path was broken, now its fixed.

llvm-svn: 178719
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>