Fix LIT test failure encountered on AIX
```
fatal error: error in backend: getLangStandardForKind() on unspecified kind
```

Clang :: Modules/preprocess-module.cpp
Clang :: Modules/no-module-map.cpp
Clang :: Modules/preprocess-build-diamond.m
Clang :: Modules/preprocess-decluse.cpp
Clang :: Modules/string_names.cpp

Fix to prior commit 7bde1c34a43d66bf38a3072c4a07795f252ccb1c, D103707
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>