[flang] Fix an unused variable warning
This patch fixes:

  flang/lib/Lower/OpenACC.cpp:876:14: error: unused variable
  'nbRangeArgs' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>