Revert D80450 "[CUDA][HIP] Fix implicit HD function resolution"
This reverts commit dd4b6820543c4109cb8e0725d5f2284c50d9be81.

This can still cause bogus errors:

eigen3/Eigen/src/Core/CoreEvaluators.h:94:38: error: call to implicitly-deleted copy constructor of 'unary_evaluator<Eigen::Inverse<Eigen::Matrix<double, 4, 4, 0, 4, 4>>>'

thrust/system/detail/generic/for_each.h:49:3: error: implicit instantiation of undefined template
'thrust::detail::STATIC_ASSERTION_FAILURE<false>'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>