[symbolizer] Change error message if module not found (recommit)
This is a recommit of 2181ae7ffa95, reverted in cd7ee5cf8c98, because
it caused compilation error in
compiler-rt/lib/sanitizer_common/symbolizer/sanitizer_symbolize.cpp.
The error was fixed by Kasimir Georgiev in 915312861388, but this
commit was reverted in 15e359928cab, because the initial commit was
reverted.

This commit reverts both the reverting commits, cd7ee5cf8c98 and
15e359928cab.

Original commit message is below.

If llvm-symbolize did not find module, the error looked like:

    LLVMSymbolizer: error reading file: No such file or directory

This message does not follow common practice: LLVMSymbolizer is not an
utility name. Also the message did not not contain the name of missed file.

With this change the error message looks differently:

    llvm-symbolizer: error: 'abc': No such file or directory

This format is closer to messages produced by other utilities and allow
proper coloring.

Differential Revision: https://reviews.llvm.org/D148032
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>