Revert "[mlir] Fix '-Wtemplate-id-cdtor'. NFC"
This reverts commit 120cdbb180114ae385b6890ee9d098b4a3ded5b3.

It breaks pre-merge CI:
```
2025-12-08T16:35:11.7239054Z /home/gha/actions-runner/_work/llvm-project/llvm-project/mlir/lib/Pass/PassRegistry.cpp:439:37: error: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [-Werror,-Wdtor-name]
2025-12-08T16:35:11.7240458Z   439 | llvm::cl::OptionValue<OpPassManager>::~OptionValue() = default;
2025-12-08T16:35:11.7241014Z       | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
2025-12-08T16:35:11.7241494Z       |                                     ::OptionValue
2025-12-08T16:35:11.7241903Z 1 error generated.
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>