Revert "[llvm][clang][bolt][NFC] Use llvm::less_first() when applicable"
This reverts commit 6abb88a037c6e966cf3b1774aec7083958c23d9e.

Did not build on this bot:
https://lab.llvm.org/buildbot#builders/215/builds/6372

/usr/include/c++/9/bits/predefined_ops.h:177:11: error: no match for call to
‘(llvm::less_first) (std::pair<long unsigned int, llvm::bolt::BinaryBasicBlock*>&, const std::pair<long unsigned int, std::nullptr_t>&)’
  177 |  { return bool(_M_comp(*__it, __val)); }
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>