Revert "Threading: Convert Optional to std::optional"
This reverts commit 657c6abff6b07c26d380e06671904efa83ff4717.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>