[LLDB] Remove unused variable 'lang_rt' in ClangExpressionParser.cpp (NFC)
/data/llvm-project/lldb/source/Plugins/ExpressionParser/Clang/ClangExpressionParser.cpp:398:34: error: variable 'lang_rt' set but not used [-Werror,-Wunused-but-set-variable]
  lldb_private::LanguageRuntime *lang_rt = nullptr;
                                 ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>