Revert "[GlobalISel][LLT] Introduce FPInfo for LLT (Enable bfloat, ppc128float and others in GlobalISel) (#155107)" (#188344)
This reverts commit e677491c821023259fd44a66d9c25ba4f0e64fc9 and commit
b8743f515e4e154f78d11851e6e244dfb1e23c0d.

This fails the build with some older gcc:

llvm/include/llvm/CodeGenTypes/LowLevelType.h:501:35: error: call to
non-constexpr function ‘static llvm::LLT llvm::LLT::integer(unsigned
int)’
     return integer(getSizeInBits());
                                   ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>