add intrinsics_gen dependence on Polly
to avoid build errors like this:
In file included from ../include/llvm/IR/IntrinsicInst.h:30:0,
                 from ../tools/polly/lib/CodeGen/BlockGenerators.cpp:28:
../include/llvm/IR/Intrinsics.h:41:34: fatal error: llvm/IR/Intrinsics.gen: No such file or directory

The earlier change in commit b1d2e6d5c3ce151ef6b7213c00019715e63d7cfb has been
accidentally reverted in:

commit 6b1963814877f5b1b161d3a73a3c8246c4ad4787
Author: simbuerg <simbuerg@91177308-0d34-0410-b5e6-96231b3b80d8>
Date:   Tue Mar 11 21:26:06 2014 +0000

    Refactor Polly's Pass creation and initialization.

    Rename some files and adjust cmake accordingly

llvm-svn: 203843
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>