[clang][ASTImporter] Fix -Wpessimizing-move in ASTImporter.cpp (NFC)
/llvm-project/clang/lib/AST/ASTImporter.cpp:371:20: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
       return std::move(Err);
              ^
/llvm-project/clang/lib/AST/ASTImporter.cpp:371:20: note: remove std::move call here
       return std::move(Err);
              ^~~~~~~~~~   ~
/llvm-project/clang/lib/AST/ASTImporter.cpp:380:22: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
         return std::move(Err);
                ^
/llvm-project/clang/lib/AST/ASTImporter.cpp:380:22: note: remove std::move call here
              return std::move(Err);
                     ^~~~~~~~~~   ~
2 errors generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>