[Vectorize] Fix a warning
This patch fixes:

  llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:1278:12: error:
  unused variable 'Op0' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>