Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit 96ff3e4afb863a8f16332305180244a0aed44b5d.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>