Revert "[InstCombine] Add support for max(a,b) + min(a,b) => a + b."
Revert commit due to failure on buildbot:
error: 'match_combine_or' may not intend to support class template argument deduction

This reverts commit 364079c4ad81047ab5352337e08bb211ff063617.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>