Revert fa36f95a701 "[builtins] Implement rounding mode support for i386/x86_64"
It broke the build with MSVC:

fp_mode.c(20): error C2065: '__asm__': undeclared identifier

> Differential Revision: https://reviews.llvm.org/D69870
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>