Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit 9ada5b8284fd67ad1351a1e8e9a66ffae1c239b3.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>