[lldb/Test] Add missing stdio.h includes
Fixes error: implicit declaration of function 'printf' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>