[clang] Remove unused lambda capture (NFC)
llvm-project/clang/lib/Serialization/ASTWriter.cpp:5077:59:
error: lambda capture 'SemaRef' is not used [-Werror,-Wunused-lambda-capture]
    auto AddEmittedDeclRefOrZero = [this, &SemaDeclRefs, &SemaRef](Decl *D) {
                                                       ~~~^~~~~~~
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>