Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit 145ae47b94b2c7a60f7983fcdfc1d4997c2ad6fc.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>