Revert "[Coverage] Revise format to reduce binary size"
This reverts commit 3ea1d39a9940aa883fb61ad7fe215c0e6f418c5e.

On Windows, there is an error:

http://lab.llvm.org:8011/builders/sanitizer-windows/builds/54963/steps/stage%201%20check/logs/stdio

error: C:\b\slave\sanitizer-windows\build\stage1\projects\compiler-rt\test\profile\Profile-x86_64\Output\instrprof-merging.cpp.tmp.v1.o: Failed to load coverage: Malformed coverage data
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>