[RISCV] Remove unused variable 'ST' in RISCVTargetMachine.cpp (NFC)
llvm-project/llvm/lib/Target/RISCV/RISCVTargetMachine.cpp:358:27:
error: unused variable 'ST' [-Werror,-Wunused-variable]
    const RISCVSubtarget &ST = C->MF->getSubtarget<RISCVSubtarget>();
                          ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>