[libcxx] Remove NODEBUG, ALWAYS_INLINE from __swap_layouts (#194931)
This addresses reviewer feedback on #180102.

We've seen

```
error: No debug information found in function
_ZNSt4__Cr6vectorIN4bssl3der5InputENS_9allocatorIS3_EEE14__swap_layoutsERNS_14__split_bufferIS3_S5_NS_29__split_buffer_pointer_layoutEEE:
Function profile not used [-Werror,-Wbackend-plugin]
```

on an internal bot due to the _LIBCPP_NODEBUG.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>