[compiler-rt] Fix a warning
This patch fixes:

  compiler-rt/lib/builtins/cpu_model.c:590:5: error: unannotated
  fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

by adding a missing "break;".
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>