[bazel] Add missing deps for #141864 (#142437)
Added in fa74b6289fe231ff0203ddceea10544c26872f36.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>