Revert "[LLD][ELF] Cortex-M Security Extensions (CMSE) Support"
This reverts commit 2658e3ae1b33214e2e42db009210b7ed76cb0b0f.

I am reverting this for now until I figure out how to fix
the build bot errors and warnings.

Errors:
llvm-project/lld/ELF/Arch/ARM.cpp:1300:29: error: expected primary-expression before ‘>’ token
 osec->writeHeaderTo<ELFT>(++sHdrs);

Warnings:
llvm-project/lld/ELF/Arch/ARM.cpp:1306:31: warning: left operand of comma operator has no effect [-Wunused-value]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>