[flang] Fix warnings
This patch fixes:

  flang/../mlir/include/mlir/IR/TypeRange.h:51:19: error: 'ArrayRef'
  is deprecated: Use {} or ArrayRef<T>() instead
  [-Werror,-Wdeprecated-declarations]

  flang/../mlir/include/mlir/IR/ValueRange.h:401:20: error: 'ArrayRef'
  is deprecated: Use {} or ArrayRef<T>() instead
  [-Werror,-Wdeprecated-declarations]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>