Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit c385da33fcd2e54a0e9caa8230611f3814692612.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>