Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit c33c8e0a2c0165607d56e05709c04885d14af8a4.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>