[llvm] Undo change to constructor in OptSubCommand example
Originally done in #166088.

This broke 2 of our Flang builds with this error:
FAILED: examples/OptSubcommand/CMakeFiles/OptSubcommand.dir/llvm-hello-sub.cpp.o
/usr/local/bin/c++ <..> -c /home/tcwg-buildbot/worker/flang-aarch64-rel-assert/llvm-project/llvm/examples/OptSubcommand/llvm-hello-sub.cpp
../llvm-project/llvm/examples/OptSubcommand/llvm-hello-sub.cpp:49:51: error: expected '{' or ','
   49 |                         OptionSubCommandIDsTable) = default;
      |                                                   ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>