[AMDGPU] Avoid unused variable warning in Release builds. NFC.
SIRegisterInfo.cpp:480:19: error: unused variable 'SOffset'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>