[Headers] Remove a space in NULL define
There was no space in `((void *)0)` before D158709. This can cause
downstream warnings in case other libraries define `NULL` as
`((void*)0)`, which is the case for [[ https://www.musl-libc.org/ | musl ]]. (see `NULL` definition in
https://git.musl-libc.org/cgit/musl/tree/include/stdio.h)

When a macro is redefined, if the content is the same it is fine, but if
it is different even in terms of a single space, clang warns:
```
../musl/include/stdio.h:37:9: error: 'NULL' macro redefined [-Werror,-Wmacro-redefined]
   37 | #define NULL ((void*)0)
      |         ^
```

The old code didn't have the space and it had been fine for many years,
so I think there's no risk in removing it. The linter seems to prefer
the space in there, but I think it has a risk of causing warnings or
even errors for downstream users.

Reviewed By: iana

Differential Revision: https://reviews.llvm.org/D159312
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>