[flang] Fix a warning
This patch fixes:

  flang/lib/Optimizer/Transforms/AddAliasTags.cpp:169:27: error:
  unused function 'operator<<' [-Werror,-Wunused-function]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>