Revert "Add a pass to collect dropped var stats for MIR. (#115566)"
This reverts commit a39c59c3251e7e41ba7725701945f3b019ba63bc.

Reverting due to buildbot failure:

unittests/IR/CMakeFiles/IRTests.dir/DroppedVariableStatsIRTest.cpp.o:DroppedVariableStatsIRTest.cpp:function llvm::DroppedVariableStatsIR::runAfterPass(llvm::StringRef, llvm::Any): error: undefined reference to 'llvm::DroppedVariableStatsIR::runOnModule(llvm::Module const*, bool)'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>