[X86] Silence an unused-variable warning (NFC)
/llvm-project/llvm/lib/Target/X86/GISel/X86InstructionSelector.cpp:1054:9:
 error: unused variable 'RhsBank' [-Werror,-Wunused-variable]
  auto *RhsBank = RBI.getRegBank(RhsReg, MRI, TRI);
        ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>