Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 3cfd40fa5051fb4b1e6bab1807aac6a02a4052d3.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>