Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit 73c518e82e4155188b506f4017b1467e206a8826.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>