Revert "[YAML][NFC] precommit wrong test case (#131782)"
This reverts commit ffb85e9a5131958e96495eed2a079381d880d4e7.

That commit broke compilation with GCC:

../unittests/Support/YAMLIOTest.cpp:1280:20: error: explicit specialization of
template<class T> struct llvm::yaml::MappingTraits’ outside its namespace must u
se a nested-name-specifier [-fpermissive]
 1280 | template <> struct MappingTraits<V> {
      |                    ^~~~~~~~~~~~~~~~
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>