[AsmPrinter] Fix a warning
This patch fixes:

  llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp:3575:44: error:
  missing field 'Cases' initializer
  [-Werror,-Wmissing-field-initializers]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>