Revert "[AArch64] Decouple feature dependency expansion. (#94279)" (#95056)
This reverts commit f0a6ee2cf74578f0379b6ff24a9ffb8b69bbd4a1 since it
broke the llvm test suite:

SingleSource/UnitTests/AArch64/acle-fmv-features.c:59:9:
  error: instruction requires: altnzcv
SingleSource/UnitTests/AArch64/acle-fmv-features.c:117:10:
  error: instruction requires: aes
...

Looks like the FMV dependencies were used in the target attribute and
now features that are FMVOnly (have AEK_NONE) cannot be expanded in
parseTargetAttr using the ExtensionSet.

This suggests that either the tests are wrong (they are using an FMVOnly
feature in a target attribute), or that we need to turn the FMVOnly
features into Extensions (these two are tablegen classes).
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>