Revert "[msan] Check qsort input." and "[msan] Intercept qsort, qsort_r."
Temporarily revert the qsort changes because they fail to build on bots
that build with modules:

> error: thread-local storage is not supported for the current
> target (iossim)

http://green.lab.llvm.org/green/job/clang-stage2-Rthinlto/1820/console
http://green.lab.llvm.org/green/view/LLDB/job/lldb-cmake/4983/console

This reverts commit f6f92cd7eba2686e8c4bcff2de70fd9dd93391c9.
This reverts commit 9beab7ebefafef86c79e1fc6e5c9f6e51fb17e2f.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>