[InstCombine] Fix a compilation bug
With gcc 6.3.0, I hit the following compilation bug.
  ../lib/Transforms/InstCombine/InstCombineVectorOps.cpp:937:2: error: extra ‘;’ [-Werror=pedantic]
   };
    ^
  cc1plus: all warnings being treated as errors

The error is introduced by Commit 713ec2003872 ("[InstCombine]
Aggregate reconstruction simplification (PR47060)")
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>