[lldb] try to fix build on linux after 3a382b9265718
Tries to fix:

    ../../lldb/source/Breakpoint/WatchpointResource.cpp:59:12:
    error: no member named 'find' in namespace 'std'; did you mean 'fill'?
          std::find(m_constituents.begin(), m_constituents.end(), wp_sp);
          ~~~~~^~~~
               fill

(cherry picked from commit 9ba529ac5c5afc2c00b6e9729f707abfd0b3694a)
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>