Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 0854c27bd2f8a175de25e2e31ab9202285d62ec2.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>