Revert "Add symbol locator time for each module in statistics (#134563)"
This reverts commit 31a849f849a42e9c82af3d883e55c7ae59d92b5e.

Multiple buildbot failures have been reported:
https://github.com/llvm/llvm-project/pull/134563

The build fails with:

  lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared
  identifier 'num_symbols_loaded'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>