[RISCV] Remove unused private field 'HasFRMRoundModeOp' in RVVIntrinsic (NFC)
/data/llvm-project/clang/include/clang/Support/RISCVVIntrinsicUtils.h:390:8: error: private field 'HasFRMRoundModeOp' is not used [-Werror,-Wunused-private-field]
  bool HasFRMRoundModeOp;
       ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>