Revert "[llvm-exegesis] Add thread IDs to subprocess memory names (#84451)"
This reverts commit 7adf2d02de87dbb6cd9b68923aa2c47c8e98902a.

This breaks building LLVM on macOS, failing with

    llvm/tools/llvm-exegesis/lib/SubprocessMemory.cpp:146:33: error: out-of-line definition of 'setupAuxiliaryMemoryInSubprocess' does not match any declaration in 'llvm::exegesis::SubprocessMemory'
    Expected<int> SubprocessMemory::setupAuxiliaryMemoryInSubprocess(
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>