Revert "Move DroppedVariableStats to CodeGen lib (#120650)"
This reverts commit e0a799d52a0dd173e0416047dd2eafa5eb90b29c.

Broke bot ppc64le-clang-multistage-test:

undefined reference to
`llvm::DroppedVariableStats::populateVarIDSetAndInlinedMap in
In function `llvm::DroppedVariableStatsIR::visitEveryInstruction
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>