[Flang][OpenMP] Fix to variables not inheriting data sharing attributes (#79017)
When a default(none) clause exists and a threadprivate variable is used
inside the construct, the variable does not inherit threadprivate
behavior and throws the below error.

> error: The DEFAULT(NONE) clause requires that 'a' must be listed in a
data-sharing attribute clause

Added a condition to skip the error if it is a threadprivate variable.

Fixes: https://github.com/llvm/llvm-project/issues/49545
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>