[clang-tidy] Disambiguate calls to log
44b46c3bf72ec6e074353e94e864e97ac71e21f1 <https://reviews.llvm.org/rGc8644b18f570be9d26d83cdeeb2369cd3cbddaf1>
broke the Solaris/amd64 <https://lab.llvm.org/staging/#/builders/101/builds/15078>
and Solaris/sparcv9 <https://lab.llvm.org/staging/#/builders/50/builds/15116> buildbots:

  FAILED: tools/clang/tools/extra/clang-tidy/altera/CMakeFiles/obj.clangTidyAlteraModule.dir/UnrollLoopsCheck.cpp.o
  [...]
  /vol/llvm/src/llvm-project/dist/clang-tools-extra/clang-tidy/altera/UnrollLoopsCheck.cpp:217:25: error: call to 'log' is ambiguous
    217 |       Iterations = 1 + (log(EndValue) - log(InitValue)) / log(ConstantValue);
        |                         ^~~
  /usr/include/iso/math_iso.h:60:15: note: candidate function
     60 | extern double log __P((double));
        |               ^
  /usr/include/iso/math_iso.h:158:15: note: candidate function
    158 |         inline float log(float __X) { return __logf(__X); }
        |                      ^
  /usr/include/iso/math_iso.h:193:21: note: candidate function
    193 |         inline long double log(long double __X) { return __logl(__X); }
        |                            ^

Fixed by disambituating the calls with `double` casts.

Tested on `amd64-pc-solaris2.11` and `x86_64-pc-linux-gnu`.

Differential Revision: https://reviews.llvm.org/D158959
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>