[polly] Remove unused variable in ScopBuilder.cpp (NFC)
/llvm-project/polly/lib/Analysis/ScopBuilder.cpp:2725:18:
error: unused variable 'DT' [-Werror,-Wunused-variable]
  DominatorTree *DT = Stmt.getParent()->getDT();
                 ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>