Revert "[MLIR] Expose `getAsValues` in `StaticValueUtils.h` (NFC)"
This reverts commit 33c679265af6720a7b3ed8ed3a39e531c2514799.

It fails with a linking errors: `undefined reference to
`mlir::getValueOrCreateConstantIndexOp` in `libMLIRDialectUtils`.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>