Revert [llvm] annotate ABIBreakingChecks symbols for DLL export (#147965)
This patch reverts commit aad058e76f989a9c64dd6408228a16da1c00a728. The
change introduced a cyclic dependency:
```
fatal error: cyclic dependency in module 'LLVM_Utils': LLVM_Utils -> LLVM_Config_ABI_Breaking -> LLVM_Utils
```

See failure log at
https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/976/console.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>