Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit e4862fb6b569265a29c98a15c7fdf219d110ea11.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>