evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit 93cd3ebadfc4af29575d9e5a6af7f2c3ffd5749f.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>