Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit 09668289a18d927500ab0e282c6a33bd20d7e8ab. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>