[AArch64] Fix an unused variable warning
This patch fixes:

  llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:25852:12: error:
  unused variable 'MaskSize' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>