[libsycl] Fix debug build error caused by RTTI option mismatch (#210997)
Fixes an undefined reference to typeinfo for `llvm::ErrorInfoBase`
during a debug build of libsycl.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>