Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit 6ee170db9dfe781746f5425df040324dea06221a.

A bot is broken
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>