[MLIR][MPI] adding MLIRDLTIDialect when linking MLIRMPIDialect (#145316)
Fixing buildbot errors on some platforms like 
```
undefined reference to `mlir::dlti::query(mlir::Operation*, llvm::ArrayRef<llvm::StringRef>, bool)'
```
Introduced in #144716
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>