Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit ab978988246d752a981ce67cff7cd3d15292c2b2.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>