Revert "[IR][ARM] Add function pointer alignment to datalayout"
This reverts commit fdb6a87a95cd8e46720ec97c4bc22e5b76fbe3b0.

This reverts rL355522 (https://reviews.llvm.org/D57335).

Kills buildbots that use '-Werror' with the following error:
	/var/lib/buildbot/sanitizer-buildbot6/sanitizer-x86_64-linux-android/build/llvm/lib/IR/Value.cpp:657:7: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]

See buildbots http://lab.llvm.org:8011/builders/sanitizer-x86_64-linux-fast/builds/30200/steps/check-llvm%20asan/logs/stdio for more information.

llvm-svn: 355537
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>