[RISCV] Remove unused function (NFC)
/llvm-project/llvm/lib/TargetParser/RISCVTargetParser.cpp:148:1:
error: unused function 'getExtensionBitmask' [-Werror,-Wunused-function]
getExtensionBitmask(StringRef ExtName) {
^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>