[mlir] Fix an unused variable warning
This patch fixes:

  mlir/test/lib/IR/TestBytecodeRoundtrip.cpp:403:10: error: unused
  variable 'status' [-Werror,-Wunused-variable]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>