[symbolizer] Change error message if module not found (recommit)
This is a recommit of c8c50396bab8, reverted in 138cd5c886d2, because
it caused compilation error in
compiler-rt/lib/sanitizer_common/symbolizer/sanitizer_symbolize.cpp.
The error was fixed by Kasimir Georgiev in 82cb759f273d, but this
commit was reverted in 9403826a2d27, because the initial commit was
reverted.

This commit reverts both the reverting commits, 138cd5c886d2 and
9403826a2d27.

Original commit message is below.

If llvm-symbolize did not find module, the error looked like:

    LLVMSymbolizer: error reading file: No such file or directory

This message does not follow common practice: LLVMSymbolizer is not an
utility name. Also the message did not not contain the name of missed file.

With this change the error message looks differently:

    llvm-symbolizer: error: 'abc': No such file or directory

This format is closer to messages produced by other utilities and allow
proper coloring.

Differential Revision: https://reviews.llvm.org/D148032
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>