Revert "[MLIR][LLVM] Permit integer types in switch other than i32"
This reverts commit dd40a3beee4045435ca08d3a3987fe42a52a9327.
Build is broken with:

tools/mlir/include/mlir/Dialect/LLVMIR/LLVMOps.cpp.inc:23996:3: error: no matching function for call to 'printSwitchOpCases'
  printSwitchOpCases(_odsPrinter, *this, getValue().getType(), getCaseValuesAttr(), getCaseDestinations(), getCaseOperands(), getCaseOperands().getTypes());
  ^~~~~~~~~~~~~~~~~~
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>