Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 1ca4e67dd46acc6a70f40f40b29a30ec4617ca03 and
b1f34e021ce688b94ceb6ccc2693814c0756ad20.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>