[clang][analyzer] Remove unused variable in StreamChecker.cpp (NFC)
llvm-project/clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp:1125:17:
 error: unused variable 'ASTC' [-Werror,-Wunused-variable]
 1125 |     ASTContext &ASTC = C.getASTContext();
      |                 ^~~~
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>