Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit 3ecdb1156a2d8b8dbab5d5111b45d7201ed1a7d5.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>