Revert "[LLD] [COFF] Implement a GNU/ELF like -wrap option"
This reverts commit c9d189a307b083528d159e36b29efe7d43163aba.

Breaks Windows builds.

C:\src\llvm-mint\lld\COFF\Symbols.cpp(26,1): error: static_assert failed due to requirement 'sizeof(lld::coff::SymbolUnion) <= 48' "symbols should be optimized for memory usage"
static_assert(sizeof(SymbolUnion) <= 48,
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>