[Frontend] Explicitly include Bitstream/BitCodes.h and BitstreamWriter.h
This fixes a modules issue:

error: declaration of 'bitc' must be imported from module
'Clang_Serialization.ASTBitCodes' before it is required
Stream.EmitRecord(llvm::bitc::BLOCKINFO_CODE_SETBID, Record);

llvm-svn: 365405
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>