[llvm-profgen] Fix a set-but-unused warning
This patch fixes:

  llvm/tools/llvm-profgen/ProfiledBinary.cpp:357:12: error: variable
  'EndOffset' set but not used [-Werror,-Wunused-but-set-variable]

The last use of the variable was removed on Oct 26 in commit
54da47b54ec15ff6a0c607d29267ec213d516cc6.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>