Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit 4d1ae0c82832937338e35ef76d4f9729b7ffa768.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>