evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit e21991b3573143c4fa6b314de0e7c11c4d61d770.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>