Revert "[MachineScheduler] Convert some of the debug prints into using LDBG. NFC (#161997)"
This reverts commit 430b933e5b45697a65da43ccb69f0673838d7444.

This breaks builds:
 3355 |            << SchedModel->getResourceName(CurrZone.getZoneCritResIdx()) << "\n";
      |               ~~~~~~~~~~  ^
/home/buildbot/workspace/bolt-aarch64-ubuntu-clang/llvm-project/llvm/lib/CodeGen/MachineScheduler.cpp:3358:51: error: no member named 'getResourceName' in 'llvm::TargetSchedModel'
 3358 |     LDBG() << "  RemainingLimit: " << SchedModel->getResourceName(OtherCritIdx)
      |                                       ~~~~~~~~~~  ^
2 errors generated.

E.g. https://lab.llvm.org/buildbot/#/builders/128/builds/7522
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>