Revert "[YAML][NFC] precommit wrong test case (#131782)"
This reverts commit 24c27c586c7ed147164799b429abbf6463fd002f.

That commit broke compilation with GCC:

../unittests/Support/YAMLIOTest.cpp:1280:20: error: explicit specialization of
template<class T> struct llvm::yaml::MappingTraits’ outside its namespace must u
se a nested-name-specifier [-fpermissive]
 1280 | template <> struct MappingTraits<V> {
      |                    ^~~~~~~~~~~~~~~~
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>