Revert "[clang-format] Add -j to clang-format-diff to speed up formatting"
This reverts commit 6dbad7a7fa3f705f08431f752d6115b0224a16e9.

Makes clang_format_diff.py always fail with:

    Traceback (most recent call last):
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 177, in <module>
        main()
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 174, in main
        process_subprocess_result(proc, args)
      File "/home/npopov/repos/llvm-project/clang/tools/clang-format/clang-format-diff.py", line 42, in process_subprocess_result
        with open(filename) as f:
                  ^^^^^^^^
    NameError: name 'filename' is not defined
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>