[flang][OpenMP] Add explicit return type to visitor lambdas (#206588)
This should silence MSVC (14.51.36231) error:
error C2338: static assertion failed: 'visit() requires the result of
all potential invocations to have the same type and value category
(N4950 [variant.visit]/5).'

e.g. https://lab.llvm.org/buildbot/#/builders/166/builds/9664
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>