Revert "[flang] Make 'this_image()' an intrinsic function"
This reverts commit 97cceeb88c19bbbc9d2343fdbe362be2c4c8b7cb.
This seems to break the shared libs build
(linaro-flang-aarch64-sharedlibs bot) with:

  undefined reference to `Fortran::semantics::IsCoarray(Fortran::semantics::Symbol const&)

(from tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o)

When linking lib/libFortranEvaluate.so.14git
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>