Revert "[Clang] Generate test checks (NFC)"
This reverts commit 4d828fd3c04a276414024f62bf4f02e6d5ef22ca.

This is causing test failures on builds without assertions:

/data/users/smeenai/llvm-project/clang/test/Analysis/builtin_signbit.cpp:14:21: error: CHECK-BE32-NEXT: expected string not found in input
// CHECK-BE32-NEXT: entry:
                    ^

Bots are also failing, e.g. https://lab.llvm.org/buildbot/#/builders/67/builds/13266/steps/7/logs/stdio
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>