Remove unused functions in X86LegalizerInfo.cpp (NFC)
/home/jiefu/llvm-project/llvm/lib/Target/X86/X86LegalizerInfo.cpp:48:1: error: unused function 'widen_1' [-Werror,-Wunused-function]
widen_1(const LegacyLegalizerInfo::SizeAndActionsVec &v) {
^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>