[clang][dataflow] Remove unused private field 'StmtToEnv' (NFC)
llvm-project/clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp:148:23:
 error: private field 'StmtToEnv' is not used [-Werror,-Wunused-private-field]
  148 |   const StmtToEnvMap &StmtToEnv;
      |                       ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>