Revert "Don't expose unavailable cstdio functions."
Broke builders that emit different diagnostics. e.g.:

error: 'warning' diagnostics seen but not expected:
  Line 13: alias declarations are a C++11 extension
  Line 20: alias declarations are a C++11 extension

This reverts commit dbd4b3a656b32890befaf284dc056a0c4b39489f.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>