[lldb][test] Skip DIL array subscript test on Windows
This has been flaky on Linaro's Windows on Arm bot, failing
with errors all along these lines:

Traceback (most recent call last):
  File "C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\test\API\commands\frame\var-dil\basics\ArraySubscript\TestFrameVarDILArraySubscript.py", line 56, in test_subscript
    self.expect_var_path("int_arr[100]", True, type="int")
  File "C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\test\API\commands\frame\var-dil\basics\ArraySubscript\TestFrameVarDILArraySubscript.py", line 15, in expect_var_path
    value_dil = super().expect_var_path(expr, value=value, type=type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 2589, in expect_var_path
    value_check.check_value(self, eval_result, str(eval_result))
  File "C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 301, in check_value
    test_base.assertSuccess(val.GetError())
  File "C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 2597, in assertSuccess
    self.fail(self._formatMessage(msg, "'{}' is not success".format(error)))

AssertionError: 'read memory from 0x68119c00b0 failed (0 of 4 bytes read)' is not success

I think this is because we are trying to read off of the top of the
stack which is unmapped memory on Windows.

I have a fix I'm going to put in review shortly.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>