[Benchmark] Fix warnings around usage of __COUNTER__ (#184524)
Premerge CI is currently failing with the following after the update to
clang v22:

```
/home/gha/llvm-project/clang-tools-extra/clangd/benchmarks/IndexBenchmark.cpp:92:1: error: '__COUNTER__' is a C2y extension [-Werror,-Wc2y-extensions]
   92 | BENCHMARK(dexQueries);
      | ^
```

Some original work was done around this in
eac6787f55a0b3851ea6fda99902192525d797be, which was then done in
upstream Google benchmark in

https://github.com/google/benchmark/commit/d8db2f90b643eb28a12976beb4d57bcfb639911d.
The original work done in the patch implementing this feature doesn't
seem to account for as many cases as the upstream patch does. This patch
reverts the diff in eac6787f55a0b3851ea6fda99902192525d797be and applies
the applicable hunks from the upstream patch.

(cherry picked from commit aceddc61476a4ce2ac61354987dce3977a8d0785)
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>