[lldb] Fix "NameError: name 'self' is not defined" when using crashlog -c
This fixes a regression introduced by 9a696025d930 that results in a
NameError: (name 'self' is not defined) when using crashlog with the -c
option.

rdar://110007391
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>