Revert "[llvm-exegesis] Add thread IDs to subprocess memory names (#84451)"
This reverts commit 74d39e8d788e52491393c809e1e4b2bfeda3a2b6.

This breaks building LLVM on macOS, failing with

    llvm/tools/llvm-exegesis/lib/SubprocessMemory.cpp:146:33: error: out-of-line definition of 'setupAuxiliaryMemoryInSubprocess' does not match any declaration in 'llvm::exegesis::SubprocessMemory'
    Expected<int> SubprocessMemory::setupAuxiliaryMemoryInSubprocess(
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>