[flang][cuda] Break circular global init when copying them to the GPU module (#211100)
PTX does not support cycle in globals. 

```
error: Circular dependency found in global variable set
```

To avoid cycle in type descriptor, check if there is a cycle and break
it.

The algorithm uses Tarjan’s strongly connected components algorithm for
finding strongly connected components in a directed graph.
- Each fir.global is a graph node.
- Each fir.address_of in a global initializer is an edge to another
global.
- An SCC containing multiple globals—or a self-edge—represents a
circular initializer dependency.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>