[hwasan] Exclude bcmp interceptor test from Android
This fixes a buildbot breakage (e.g.,
https://lab.llvm.org/buildbot/#/builders/77/builds/31422/steps/21/logs/stdio)
that was caused by the introduction of this test
(https://github.com/llvm/llvm-project/commit/64dabc5f3219f4cea19de13e3b00693eaf0d4dd8).

Build error from buildbot:
/var/lib/buildbot/sanitizer-buildbot6/sanitizer-x86_64-linux-android/build/llvm-project/compiler-rt/test/hwasan/TestCases/bcmp.cpp:18:10: error: use of undeclared identifier 'bcmp'
   18 |   return bcmp(p, a, size);
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>