Revert "[mlir][tosa] Split tosa-to-linalg named ops out of pass"
This reverts commit 8878a3de29c2812a4a27c61eaffb5ddee8795e62.

There is a missing CMake dependency, building with shared libraries is
broken:

55.509 [45/4/3061] Linking CXX shared library lib/libMLIRTosaToLinalg.so.14git
FAILED: lib/libMLIRTosaToLinalg.so.14git
...
TosaToLinalgPass.cpp: undefined reference to `mlir::createCanonicalizerPass()'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>