[compiler-rt][profdata] Use x86 triple in instrprof-debug-info-correlate-warnings.ll (#222668)
Test added by #163254 / 06f957d3773728c48ad4a6ead8074da4b35de838.

It has been failing in Armv8 (32-bit) builds since then. I'm only just
getting to it.

warning: overriding the module target triple with
armv8a-unknown-linux-gnueabihf [-Woverride-module]
'x86-64' is not a recognized processor for this target (ignoring
processor)
'+cmov' is not a recognized feature for this target (ignoring feature)
'+cx8' is not a recognized feature for this target (ignoring feature)
<...>
error: a.c:1:0: in function main i32 (): calling convention is
hard-float, but floating-point registers are unavailable

Happens on AArch64 too, but it's not fatal there. This happens because
the ll has x86 options in it, but the RUN used whatever the host triple
was.

I don't know what's critical in this file, so I'm adding a --target x86
option to the test to fix this.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>