Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 3be0cc54cf7c456c915b2424134090a9c7c26d2e.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>