Fix unused private field warning (#91500)
After b2b0b2866b03 "[clang][CodeGen] Omit pre-opt link when post-opt is
link requested (#85672)" I'm seeing a new warning:

> BackendConsumer.h:37:22: error: private field 'FileMgr' is not used
[-Werror,-Wunused-private-field]

Remove the field since it's no longer used.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>