Revert "[MLIR] Expose `getAsValues` in `StaticValueUtils.h` (NFC)"
This reverts commit 6e2f8bc13abfaa5dde3217ea63dfa75b02068219.

It fails with a linking errors: `undefined reference to
`mlir::getValueOrCreateConstantIndexOp` in `libMLIRDialectUtils`.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>