Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 5ba62d339413975c3fefe21bd03114c7bf684aa1.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>