[mlir] Fix a deprecation warning
This patch fixes:

  mlir/include/mlir/Dialect/Affine/LoopUtils.h:332:25: error:
  'makeMutableArrayRef<mlir::scf::ForOp>' is deprecated: Use deduction
  guide instead [-Werror,-Wdeprecated-declarations]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>