Revert "[MLIR][SPIRV] Start module combiner"
This reverts commit 5d37ff3cd3577d70893da8584d0fc4a752d59137.
Build is broken with:

TestModuleCombiner.cpp:(.text._ZN12_GLOBAL__N_122TestModuleCombinerPass14runOnOperationEv+0x195): undefined reference to `mlir::spirv::combine(llvm::MutableArrayRef<mlir::spirv::ModuleOp>, mlir::OpBuilder&, llvm::function_ref<void (mlir::spirv::ModuleOp, llvm::StringRef, llvm::StringRef)>)'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>