[sanitizer_common] Make sanitizer_linux.cpp kernel_stat* handling Linux-specific
996675502bfca28279e9e3e2f47f4201242bf447 broke the Solaris/sparcv9 buildbot:
```
compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:39:14: fatal error: 'asm/unistd.h' file not found
   39 | #    include <asm/unistd.h>
      |              ^~~~~~~~~~~~~~
```
That section should have been Linux-specific in the first place, which is
what this patch does.

Tested on sparcv9-sun-solaris2.11.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>