[llvm-profgen] Fix a set-but-unused warning
This patch fixes:

  llvm/tools/llvm-profgen/ProfiledBinary.cpp:357:12: error: variable
  'EndOffset' set but not used [-Werror,-Wunused-but-set-variable]

The last use of the variable was removed on Oct 26 in commit
db1d687f625713ff7931fe4445e3b9559897bade.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>