[AArch64] Fix strict weak ordering violation in regalloc hints sort. (#192055)
This fixes an error with expensive checks after landing #190139.

The issue was:

Error: comparison doesn't meet irreflexive requirements, assert(!(a <
a)).

because it could have previously returned 'true' in the ordering
function if registers A and B were equal.

Also made NFC change to rename 'HandleMatchCmpPredicateHint' ->
'HandleDestructivePredicateHint' (that was missed in the review).
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>