[BOLT] Upgrade to C++17
Without this patch, I am getting errors like:

  llvm-project/llvm/include/llvm/ADT/StringRef.h:233:7: error: use of
  the 'nodiscard' attribute is a C++17 extension
  [-Werror,-Wc++17-extensions]

Differential Revision: https://reviews.llvm.org/D131348
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>