Fix llvm-objcopy shared lib build
Fix after 848eccbfd644 ("[llvm-objcopy][COFF] Fix section name
encoding", 2022-02-21) caused "undefined reference to
`llvm::COFF::encodeSectionName" failures.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>