Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit 1c20f2822a8a09809408b138515cd790e3870389.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>