Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit 8a13bf17a77c7d20625c44aee5bbffc1dd39ce18.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>