Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit bef32a28fde9d65e8710ff8a1e15fa1c57e327c5.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>