Revert "[ubsan] Simplify ubsan_GetStackTrace"
This reverts commit 63d21bea47a718536d5ed47d805b95c709454f55.

I don't quite understand why, but this causes a linker error for
me and a number of buildbots:

/home/npopov/repos/llvm-project/compiler-rt/lib/ubsan/../sanitizer_common/sanitizer_stacktrace.h:130: error: undefined reference to '__sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int)'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>