[SelectionDAG] Fix missing lambda capture
Move MaxDepth into the lambda, since it is not needed outside. This
fixes some compilers that complain about missing capture:

  error C3493: 'MaxDepth' cannot be implicitly captured because no
  default capture mode has been specified

Fixes: 18fddd86a64c ("[SelectionDAG] Transitively copy NodeExtraInfo on RAUW")
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>