Revert "[HIP] fix host min/max in header (#82956)"
This reverts commit 7d2fc5916817e8937b080f0682c1d355f662c53b.

Due to regressions in hipCUB.

hipCUB/hipcub/include/hipcub/backend/rocprim/device/device_spmv.hpp:142:33: error: call to 'min' is ambiguous

https://github.com/ROCm/hipCUB/blob/develop/hipcub/include/hipcub/backend/rocprim/device/device_spmv.hpp#L142

The ambuguity seems due to missing min(int, unsigned int).

Previously, there is only min(int, int). After the change,
there are min(int, int) and min(unsigned int, unsigned int),
therefore there is ambiguity.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>