Revert "[mlir][linalg] Support parsing attributes in named op spec"
This reverts commit 57e10b6be52cba0d5a6e20160fd2a82a496fbf2c.

The gcc-5 build was broken by this change:

  mlir/tools/mlir-linalg-ods-gen/mlir-linalg-ods-gen.cpp:1275:77:   required from here
  /usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to 'std::pair<const std::__cxx11::basic_string<char>, {anonymous}::TCParser::RegisteredAttr>::pair(llvm::StringRef&, {anonymous}::TCParser::RegisteredAttr'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>