[SystemZ][z/OS] Add guard for SI_USER  (#213101)
SI_USER is not defined on z/OS and is causing the following build
failure. `error: use of undeclared identifier 'SI_USER'` 
This patch adds a guard to check whether SI_USER is defined
before using it.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>