[AMDGPU] Remove unused variables in SILowerSGPRSpills.cpp (NFC)
/llvm-project/llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp:172:25:
error: unused variable 'RI' [-Werror,-Wunused-variable]
  const SIRegisterInfo *RI = ST.getRegisterInfo();
                        ^
1 error generated.
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>