Revert "PR47792: Include the type of a pointer or reference non-type template"
This reverts commit 24330a9c3bd49f5e092581bea9a4968396abf024 because it
results in a stage 2 build failure:

llvm-project/clang/include/clang/AST/ExternalASTSource.h:409:20: error:
definition with same mangled name
'_ZN5clang25LazyGenerationalUpdatePtrIPKNS_4DeclEPS1_XadL_ZNS_17ExternalASTSource19CompleteRedeclChainES3_EEE9makeValueERKNS_10ASTContextES4_'
as another definition

  static ValueType makeValue(const ASTContext &Ctx, T Value);
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>