[lldb] Add missing wasm switch case
TypeSystemClang.cpp:4855:13: error: enumeration value 'WasmExternRef' not handled in switch [-Werror,-Wswitch]
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>