Revert "Reland "[NFC] Move DroppedVariableStats to its own file and redesign it to be extensible. (#117042)" (#118546)"
This reverts commit 6859c386a17a16b5e6a26556c160236666ec6600.

Broke Bot: https://lab.llvm.org/buildbot/#/builders/76/builds/5008

error: undefined reference to `vtable for llvm::DroppedVariableStatsIR'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>