Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit e6adfd37b2c8a70756265edb81de79a3135f2c02.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>